import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "OnlyLeft"

[font.bold]
family = "MesloLGMDZ Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGMDZ Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGMDZ Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGMDZ Nerd Font"
style = "Regular"

[keyboard]
bindings = [
{ key = "Right", mods = "Alt", chars = "\u001BF" },
{ key = "Left", mods = "Alt", chars = "\u001BB" },
]
