local map = vim.keymap.set

-- Move lines (preserved from prior config)
map("n", "<A-j>", "<cmd>m .+1<cr>==", { desc = "Move line down" })
map("n", "<A-k>", "<cmd>m .-2<cr>==", { desc = "Move line up" })
map("i", "<A-j>", "<esc><cmd>m .+1<cr>==gi", { desc = "Move line down" })
map("i", "<A-k>", "<esc><cmd>m .-2<cr>==gi", { desc = "Move line up" })
map("v", "<A-j>", ":m '>+1<cr>gv=gv", { desc = "Move line down" })
map("v", "<A-k>", ":m '<-2<cr>gv=gv", { desc = "Move line up" })

-- Save (overrides default <C-s> insert-mode signature help)
map({ "n", "i", "x", "s" }, "<C-s>", "<cmd>w<cr><esc>", { desc = "Save file" })

-- Clear search highlight on <Esc>
map({ "i", "n" }, "<esc>", "<cmd>noh<cr><esc>", { desc = "Escape and clear hlsearch" })

-- Better up/down (handle wrapped lines)
map({ "n", "x" }, "j", "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
map({ "n", "x" }, "k", "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })

map("n", "<S-h>", "<cmd>bprevious<cr>", { desc = "Prev buffer" })
map("n", "<S-l>", "<cmd>bnext<cr>", { desc = "Next buffer" })
map("n", "[b", "<cmd>bprevious<cr>", { desc = "Prev buffer" })
map("n", "]b", "<cmd>bnext<cr>", { desc = "Next buffer" })
map("n", "<leader>bd", "<cmd>bdelete<cr>", { desc = "Delete buffer" })
map("n", "<leader>bb", "<cmd>e #<cr>", { desc = "Switch to other buffer" })

map("n", "<C-h>", "<C-w>h", { desc = "Go to left window" })
map("n", "<C-j>", "<C-w>j", { desc = "Go to lower window" })
map("n", "<C-k>", "<C-w>k", { desc = "Go to upper window" })
map("n", "<C-l>", "<C-w>l", { desc = "Go to right window" })
map("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Increase window height" })
map("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Decrease window height" })
map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease window width" })
map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase window width" })
map("n", "<leader>-", "<C-w>s", { desc = "Split window below" })
map("n", "<leader>|", "<C-w>v", { desc = "Split window right" })
map("n", "<leader>wd", "<C-w>c", { desc = "Delete window" })
map("n", "<leader>qq", "<cmd>qa<cr>", { desc = "Quit all" })
map("n", "]d", function() vim.diagnostic.jump({ count = 1, float = true }) end, { desc = "Next diagnostic" })
map("n", "[d", function() vim.diagnostic.jump({ count = -1, float = true }) end, { desc = "Prev diagnostic" })
map("n", "]e", function() vim.diagnostic.jump({ count = 1, float = true, severity = vim.diagnostic.severity.ERROR }) end, { desc = "Next error" })
map("n", "[e", function() vim.diagnostic.jump({ count = -1, float = true, severity = vim.diagnostic.severity.ERROR }) end, { desc = "Prev error" })
map("n", "]w", function() vim.diagnostic.jump({ count = 1, float = true, severity = vim.diagnostic.severity.WARN }) end, { desc = "Next warning" })
map("n", "[w", function() vim.diagnostic.jump({ count = -1, float = true, severity = vim.diagnostic.severity.WARN }) end, { desc = "Prev warning" })
map("n", "<leader>cd", vim.diagnostic.open_float, { desc = "Line diagnostics" })

local function fzf(name)
  return function() require("fzf-lua")[name]() end
end

map("n", "<leader><space>", fzf("files"), { desc = "Find files" })
map("n", "<leader>ff", fzf("files"), { desc = "Find files" })
map("n", "<leader>fg", fzf("git_files"), { desc = "Find git files" })
map("n", "<leader>fr", fzf("oldfiles"), { desc = "Recent files" })
map("n", "<leader>fb", fzf("buffers"), { desc = "Buffers" })
map("n", "<leader>,", fzf("buffers"), { desc = "Buffers" })
map("n", "<leader>/", fzf("live_grep"), { desc = "Grep" })
map("n", "<leader>sg", fzf("live_grep"), { desc = "Grep" })
map("n", "<leader>sw", fzf("grep_cword"), { desc = "Grep word under cursor" })
map("v", "<leader>sw", fzf("grep_visual"), { desc = "Grep selection" })

map("n", "<leader>sh", fzf("helptags"), { desc = "Help tags" })
map("n", "<leader>sk", fzf("keymaps"), { desc = "Keymaps" })
map("n", "<leader>sm", fzf("marks"), { desc = "Marks" })
map("n", "<leader>sj", fzf("jumps"), { desc = "Jumps" })
map("n", "<leader>sc", fzf("command_history"), { desc = "Command history" })
map("n", "<leader>sC", fzf("commands"), { desc = "Commands" })
map("n", "<leader>s:", fzf("search_history"), { desc = "Search history" })
map("n", "<leader>sR", fzf("resume"), { desc = "Resume last picker" })
map("n", "<leader>sd", fzf("diagnostics_document"), { desc = "Document diagnostics" })
map("n", "<leader>sD", fzf("diagnostics_workspace"), { desc = "Workspace diagnostics" })
map("n", "<leader>:", fzf("command_history"), { desc = "Command history" })
map("n", "<leader>gs", fzf("git_status"), { desc = "Git status" })
map("n", "<leader>gc", fzf("git_commits"), { desc = "Git commits" })
map("n", "<leader>gB", fzf("git_branches"), { desc = "Git branches" })

map("n", "-", "<cmd>Oil<cr>", { desc = "Open parent directory (oil)" })
map("n", "<leader>e", "<cmd>Oil<cr>", { desc = "Open file explorer (oil)" })
map("n", "<leader>E", function() require("oil").open(vim.fn.getcwd()) end, { desc = "Open file explorer (cwd)" })
